name = "Basic CLI"
kickstart_version = 1

[[variables]]
name = "bin_name"
default = "bin"
prompt = "Binary name?"

[[variables]]
name = "description"
default = "Some CLI app"
prompt = "A description for that binary?"

[[variables]]
name = "author_name"
default = "Ann O'Nyme"
prompt = "Your name?"

[[variables]]
name = "author_mail"
default = "spam@spam.com"
prompt = "Your email?"

[[variables]]
name = "use_clap"
default = true
prompt = "Do you want to setup clap?"

